FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN cat .env

CMD ["sh", "-c", "echo yes | cocoindex setup main.py && cocoindex update main.py && python main.py"]
